### ISSUE TITLE
主页面数据全部归零

### ISSUE THREAD

**Issue by QianFuv** [kongxiangyiren/vercel-githubcalendar#2]
![image](https://github.com/kongxiangyiren/vercel-githubcalendar/assets/111696321/3b8430f0-85dd-4b8e-a29d-326851e79d6a)

**Comment by QianFuv** [comment]
测试网址：https://blog.qianf.fun/

**Comment by kongxiangyiren** [comment]
GitHub更新导致，已修改，请重新部署
![image](https://github.com/kongxiangyiren/vercel-githubcalendar/assets/72970235/32e726b9-ec1f-47d8-9412-b0e7d3622e2d)

**Comment by QianFuv** [comment]
已解决 感谢
